from pathlib import Path
import re

p=Path('lkpd.html')
s=p.read_text(encoding='utf-8')
old='''<div class="field"><label>Jumlah soal</label><select id="jumlah"><option>10</option><option>15</option><option selected>20</option><option>25</option><option>30</option></select></div><div class="field"><label>Komposisi</label><select id="komposisi"><option value="campur">Campuran PG + Isian + Essay</option><option value="pg">PG dominan</option><option value="isian">Isian dominan</option><option value="essay">Essay dominan</option></select></div>'''
new='''<div class="field"><label>Jumlah Pilihan Ganda</label><select id="jumlahPg"><option>0</option><option>5</option><option>10</option><option selected>15</option><option>20</option><option>25</option><option>30</option></select></div><div class="field"><label>Jumlah Isian</label><select id="jumlahIsian"><option>0</option><option selected>5</option><option>10</option><option>15</option><option>20</option><option>25</option><option>30</option></select></div><div class="field"><label>Jumlah Essay</label><select id="jumlahEssay"><option selected>0</option><option>5</option><option>10</option><option>15</option><option>20</option><option>25</option><option>30</option></select></div><div class="field"><label>Jenis Asesmen</label><select id="asesmen"><option value="formatif" selected>Formatif</option><option value="sumatif">Sumatif</option></select></div><div class="field"><label>Versi LKPD</label><select id="versi"><option value="siswa" selected>Siswa — tanpa kunci</option><option value="guru">Guru — dengan kunci jawaban</option></select></div>'''
if old in s:
    s=s.replace(old,new,1)
old_stage='''<div class="stage card"><div id="paper" class="paper f4"><div style="height:100%;display:grid;place-items:center;color:#94a3b8;text-align:center"><div><b>LKPD akan muncul di sini</b><br><small>Pilih kelas, mapel, bab dan subbab lalu Generate.</small></div></div></div></div>'''
new_stage='''<div class="stage card"><div id="paper" class="paper f4"><div style="height:100%;display:grid;place-items:center;color:#94a3b8;text-align:center"><div><b>LKPD akan muncul di sini</b><br><small>Pilih kelas, mapel, bab dan subbab lalu Generate.</small></div></div></div><div id="answerPaper" class="answer-paper" hidden></div></div>'''
if old_stage in s:
    s=s.replace(old_stage,new_stage,1)
css='''.answer-paper{width:min(816px,100%);margin:18px auto 0;background:#fff;border:1px solid #cbd5e1;padding:22px;font-family:Arial,sans-serif}.answer-paper h3{margin:0 0 10px;color:#166534}.answer-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:6px 18px}.answer-item{font-size:12px;line-height:1.35;padding:6px 0;border-bottom:1px dashed #cbd5e1}.answer-item b{color:#166534}.answer-note{font-size:11px;color:#64748b;margin-bottom:10px}@media print{.answer-paper{break-before:page;border:0;margin:0;padding:12mm;width:auto}}'''
if '.answer-paper{' not in s:
    s=s.replace('@media print{body{background:#fff}',css+'@media print{body{background:#fff}',1)

s2=re.sub(r"function comp\(n\)\{.*?\}function parse", "function comp(n){return[+$('jumlahPg').value,+$('jumlahIsian').value,+$('jumlahEssay').value]}function totalSoal(){return comp(0).reduce((a,b)=>a+b,0)}function parse", s, count=1)
if s2!=s:s=s2
s=s.replace("visual_description:q.visual_description||''}))}}", "visual_description:q.visual_description||'',answer:q.answer||q.kunci||q.jawaban||''}))}}",1)
s=s.replace("return`Kelas ${k} (Fase ${phase(k)}), ${m}, Bab/Materi: ${b}, Subbab/Topik: ${s}. Subbab yang tersedia:", "return`Kelas ${k} (Fase ${phase(k)}), ${m}, Jenis asesmen: ${$('asesmen').value}, Bab/Materi: ${b}, Subbab/Topik: ${s}. Subbab yang tersedia:",1)
s=s.replace("const n=+$('jumlah').value,[pg,is,es]=comp(n)", "const n=+$('jumlahPg').value+$('jumlahIsian').value+$('jumlahEssay').value,[pg,is,es]=comp(n)",1)
s=s.replace('''options:["opsi A","opsi B","opsi C","opsi D"],"visual":false,"visual_type":"foodweb|plant|math|science|water|space|sport|civic|none","visual_description":""''','''options:["opsi A","opsi B","opsi C","opsi D"],"answer":"jawaban benar","visual":false,"visual_type":"foodweb|plant|math|science|water|space|sport|civic|none","visual_description":""''',1)
s=s.replace("Tepat ${count} questions.`,", "Kunci jawaban wajib diisi untuk setiap soal. Untuk PG tulis A/B/C/D beserta teks singkat; untuk isian/essay tulis jawaban ideal atau pedoman penskoran ringkas. Tepat ${count} questions.`,",1)
s=s.replace("tujuan:'LKPD satu lembar '+$('kertas').value.toUpperCase(),durasi:'40 menit'", "tujuan:'LKPD satu lembar '+$('kertas').value.toUpperCase(),durasi:'40 menit',jenisAsesmen:$('asesmen').value",1)
s=s.replace("if(!$('kelas').value||!$('mapel').value||!$('bab').value||!$('subbab').value)return status('Pilih kelas, mapel, bab dan subbab terlebih dahulu.');const n=+$('jumlah').value;", "if(!$('kelas').value||!$('mapel').value||!$('bab').value||!$('subbab').value)return status('Pilih kelas, mapel, bab dan subbab terlebih dahulu.');const n=totalSoal();if(!n)return status('Isi jumlah soal PG, Isian, atau Essay minimal satu.');if(n>30)return status('Maksimal 30 soal agar tetap rapi dalam satu halaman.');",1)
s=s.replace("function render(d){const n=+$('jumlah').value", "function render(d){window.__lastLKPD=d;const n=totalSoal()",1)
s=s.replace("esc($('subbab').value)+'</div></div><div class=\"identity\">", "esc($('subbab').value)+' • '+esc($('asesmen').value.toUpperCase())+'</div></div><div class=\"identity\">",1)
old_tail="h+='</div><div class=\"foot\"><span>Kerjakan dengan jujur • Semangat belajar!</span><span>'+qs.length+' soal • 1 lembar '+$('kertas').value.toUpperCase()+'</span></div>';$('paper').innerHTML=h}"
new_tail="h+='</div><div class=\"foot\"><span>Kerjakan dengan jujur • Semangat belajar!</span><span>'+qs.length+' soal • 1 lembar '+$('kertas').value.toUpperCase()+'</span></div>';$('paper').innerHTML=h;const ap=$('answerPaper');if($('versi').value==='guru'){ap.hidden=false;ap.innerHTML='<h3>🔑 KUNCI JAWABAN GURU</h3><div class=\"answer-note\">'+esc($('mapel').value)+' • Kelas '+esc($('kelas').value)+' • '+esc($('bab').value)+' • '+esc($('subbab').value)+' • '+esc($('asesmen').value.toUpperCase())+'</div><div class=\"answer-grid\">'+qs.map((q,i)=>'<div class=\"answer-item\"><b>'+String(i+1)+'. '+esc(q.type==='essay'?'Essay':q.type==='isian'?'Isian':'PG')+'</b> — '+esc(q.answer||'Kunci belum tersedia')+'</div>').join('')+'</div>'}else{ap.hidden=true;ap.innerHTML=''}}"
if old_tail in s:s=s.replace(old_tail,new_tail,1)
old_png="$('png').onclick=async()=>{if(!window.html2canvas)return status('Mesin PNG belum siap.');status('Menyiapkan PNG...',true);try{const c=await html2canvas($('paper'),{scale:2,backgroundColor:'#fff',useCORS:true}),a=document.createElement('a');a.download='LKPD-'+$('mapel').value+'-Kelas-'+$('kelas').value+'-'+$('kertas').value+'.png';a.href=c.toDataURL('image/png');a.click();status('PNG berhasil dibuat.')}catch(e){status('Gagal membuat PNG: '+e.message)}};paperSize();"
new_png="$('png').onclick=async()=>{if(!window.html2canvas)return status('Mesin PNG belum siap.');status('Menyiapkan PNG...',true);try{const save=(canvas,name)=>{const a=document.createElement('a');a.download=name;a.href=canvas.toDataURL('image/png');a.click()};const c=await html2canvas($('paper'),{scale:2,backgroundColor:'#fff',useCORS:true});save(c,'LKPD-'+$('mapel').value+'-Kelas-'+$('kelas').value+'-'+$('versi').value+'.png');if($('versi').value==='guru'&&!$('answerPaper').hidden){const ca=await html2canvas($('answerPaper'),{scale:2,backgroundColor:'#fff',useCORS:true});save(ca,'Kunci-Jawaban-'+$('mapel').value+'-Kelas-'+$('kelas').value+'.png')}status('PNG berhasil dibuat.')}catch(e){status('Gagal membuat PNG: '+e.message)}};$('versi').onchange=()=>{if(window.__lastLKPD)render(window.__lastLKPD)};paperSize();"
if old_png in s:s=s.replace(old_png,new_png,1)
old_map="function refreshMapel(){const k=+$('kelas').value;fill($('mapel'),Object.keys(curriculum).filter(m=>curriculum[m][k]),'Pilih mata pelajaran');refreshBab()}"
new_map="function currentMapelRole(){try{const x=JSON.parse(localStorage.getItem('siLogin')||'null');const u=x?.user||x;return String(u?.role||'').toLowerCase()==='guru_mapel'?String(u?.mapel||''):''}catch{return ''}}function refreshMapel(){const k=+$('kelas').value,own=currentMapelRole();fill($('mapel'),Object.keys(curriculum).filter(m=>curriculum[m][k]&&(!own||m===own)),'Pilih mata pelajaran');refreshBab()}"
if old_map in s:s=s.replace(old_map,new_map,1)
s=s.replace("$('sample').onclick=()=>{$('materi').value", "$('sample').onclick=()=>{$('jumlahPg').value=15;$('jumlahIsian').value=5;$('jumlahEssay').value=0;$('materi').value",1)
p.write_text(s,encoding='utf-8')
