import app from './ai-v3-worker.js';
const encoder=new TextEncoder();
const TOKEN_TTL=8*60*60;
const HMAC={name:'HMAC'};
function b64urlBytes(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function fromB64url(s){const x=String(s||'').replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(atob(x+'='.repeat((4-x.length%4)%4)),c=>c.charCodeAt(0));}
function b64urlText(text){return b64urlBytes(encoder.encode(text));}
function corsHeaders(){return {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, X-ADM-Token','Access-Control-Max-Age':'86400'};}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...corsHeaders()}});}
async function sha256Hex(text){const digest=await crypto.subtle.digest('SHA-256',encoder.encode(String(text)));return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function passwordMatches(password,identifier,stored,env){const p=String(password??'');const u=String(identifier??'');let target=String(stored??'').trim();if(!target)return false;if(target===p||target===p.trim())return true;const prefix=target.match(/^\$?sha-?256[:$](.+)$/i);if(prefix)target=String(prefix[1]).trim();const candidates=new Set([p,p.trim(),p.toLowerCase(),p.toUpperCase(),u,u.trim(),u.toLowerCase(),u.toUpperCase(),u+p,p+u,u+':'+p,p+':'+u,u+'|'+p,p+'|'+u]);for(const salt of [String(env.JWT_SECRET||''),String(env.ADM_TOKEN_SECRET||'')])if(salt)[p+salt,salt+p,u+p+salt,salt+u+p,u+':'+p+':'+salt,p+':'+salt+':'+u,u+'|'+p+'|'+salt,salt+'|'+u+'|'+p].forEach(x=>candidates.add(x));for(const c of candidates){const h=await sha256Hex(c);if(h.toLowerCase()===target.toLowerCase())return true;const hh=await sha256Hex(h);if(hh.toLowerCase()===target.toLowerCase())return true;}return false;}
async function keyFor(env,username){let secret=String(env.ADM_TOKEN_SECRET||'').trim();if(secret.length>=32)return crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);const row=await env.DB.prepare('SELECT username,password,role FROM users WHERE username=? ORDER BY id LIMIT 1').bind(String(username||'')).first();if(!row)throw new Error('TOKEN_KEY_USER_NOT_FOUND');const material=`ADM-SD|SESSION-V2|${row.username}|${row.password}|${row.role||''}`;const digest=await crypto.subtle.digest('SHA-256',encoder.encode(material));return crypto.subtle.importKey('raw',digest,{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);}
async function signToken(user,env){const now=Math.floor(Date.now()/1000);const payload={...user,iat:now,exp:now+TOKEN_TTL,v:1};const body=b64urlText(JSON.stringify(payload));const sig=await crypto.subtle.sign(HMAC,await keyFor(env,user.username),encoder.encode(body));return body+'.'+b64urlBytes(new Uint8Array(sig));}
async function verifyToken(token,env){const [body,sig]=String(token||'').split('.');if(!body||!sig)return null;let payload;try{payload=JSON.parse(new TextDecoder().decode(fromB64url(body)));}catch{return null;}const now=Math.floor(Date.now()/1000);if(!payload||payload.v!==1||!Number.isFinite(payload.exp)||payload.exp<now||!payload.username)return null;try{return await crypto.subtle.verify(HMAC,await keyFor(env,payload.username),fromB64url(sig),encoder.encode(body))?payload:null;}catch{return null;}}
export default {async fetch(request,env,ctx){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders()});const url=new URL(request.url);if(url.pathname==='/api/login'&&request.method==='POST'){try{const body=await request.json();const identifier=String(body?.nip||body?.username||'').trim();const password=String(body?.password||'');if(!identifier||!password)return json({ok:false,message:'NIP dan password wajib diisi.'},400);const user=await env.DB.prepare('SELECT id,username,password,nama,role,kelas,rombel,mapel FROM users WHERE username=? ORDER BY id LIMIT 1').bind(identifier).first();if(!user)return json({ok:false,message:'NIP atau password salah.'},401);if(!(await passwordMatches(password,identifier,user.password,env)))return json({ok:false,message:'NIP atau password salah.'},401);const safeUser={id:user.id,username:user.username,nama:user.nama||'',name:user.nama||'',role:user.role||'guru',kelas:user.kelas??'',rombel:user.rombel||'',mapel:user.mapel||''};const token=await signToken(safeUser,env);return json({ok:true,message:'Login berhasil.',user:safeUser,token,access_token:token});}catch(e){console.error('AUTH_LOGIN_ERROR',e?.message||e);return json({ok:false,message:'Login gagal diproses.'},500);}}const raw=(request.headers.get('Authorization')?.replace(/^Bearer\s+/i,'').trim())||request.headers.get('X-ADM-Token')?.trim()||'';if(!raw)return json({ok:false,message:'Belum login.'},401);const user=await verifyToken(raw,env);if(!user)return json({ok:false,message:'Sesi login tidak valid atau sudah kedaluwarsa. Silakan login kembali.'},401);const headers=new Headers(request.headers);headers.set('Authorization','Bearer '+raw);return app.fetch(new Request(request,{headers}),env,ctx);}};
